{% set name = "jsonrpcclient" %}
{% set version = "3.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a17d02a53061748384b15b4e9812e866d5f69771656ccf7031d6dc64d0c38099

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - jsonrpc=jsonrpcclient.__main__:main
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - apply_defaults <1
    - click <7
    - jsonschema <4

test:
  imports:
    - jsonrpcclient

about:
  home: https://github.com/bcb/jsonrpcclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Send JSON-RPC requests in Python.
  doc_url: https://jsonrpcclient.readthedocs.io/
  dev_url: https://github.com/bcb/jsonrpcclient

extra:
  recipe-maintainers:
    - bcb
